### ISSUE TITLE
"Adhérents connectez-vous" dans l'onglet "réseau prisme"

### ISSUE THREAD

**Issue by daniel-menard** [docalist/docalist#26]
Sur l'onglet Prisme, on a dans la sidebar d'entête la mention "Adhérents Prisme : Connectez-vous pour profiter de l'ensemble des services disponibles".

Tant qu'on n'a pas la saisie en ligne, ce n'est pas très pertinent... Peut-être qu'il vaudrait mieux, pour le moment, enlever la mention et mettre le formulaire de recherche standard ?

**Comment by Nicolas-L** [comment]
This issue was moved to reseau-prisme/site#4
