### ISSUE TITLE
Affiner les styles des titres

### ISSUE THREAD

**Issue by daniel-menard** [docalist/docalist#3]
![image](https://f.cloud.github.com/assets/3940667/908904/04209540-fdab-11e2-9a28-c3bf296f4039.png)

Est-ce possible d’affiner les styles des Titres, Paragraphe, etc. ? Exemple ci-dessus : les Titres 1 et 2 sont identiques

(page http://www.documentation-sociale.net/doc-sociale/)
(e-mail de Nicolas du 03-08-13)

**Comment by Nicolas-L** [comment]
This issue was moved to reseau-prisme/site#2
