### ISSUE TITLE
Grille Congrès Colloque

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#305]
Lorsque l'on veut paramétrer le formulaire de saisie du type Congrès colloque, nous avons un message d'erreur
Fatal error: Call to undefined method Docalist\Type\String::editSettings() in /var/www/documentation-sociale.net/plugins/docalist-biblio/views/grid/edit.php on line 171

Idem pour la modification de l'affichage court
 Fatal error: Call to undefined method Docalist\Type\String::displaySettings() in /var/www/documentation-sociale.net/plugins/docalist-biblio/views/grid/edit.php on line 174

Sur le .net et le .org

**Comment by Nicolas-L** [comment]
Après vérification, cela concerne les type de notices suivantes :  
- Sur le .ORG : Legislation / Congrès colloque / Numéro de périodique / Rapport colloque
- Sur le .NET : Congrès colloque / Numéro de périodique / Rapport

**Comment by daniel-menard** [comment]
Le bug est dû à un manque de cohérence dans les grilles des différents types : certains champs figurent dans les formulaires ou dans les formats d'affichage alors qu'ils n'existent pas dans le type.

Je pense que ces problèmes ont été introduits lorsque nous avons procédé à la refonte des grilles prédéfinies (cf. #180).

J'ai repassé en revue les différentes grilles de tous les types et j'ai pointé les problèmes suivants : 

- type `meeting` (congrès / colloque) : 
  - le champ `event` figure dans le formulaire de saisie alors qu'il ne figure pas dans la grille de base du type
  - le champ `othertitle` figure dans la grille "affichage court" alors qu'il ne figure pas dans la grille de base

- type `periodical-issue` (numéro de périodique) : 
  - le champ `author` figure dans l'affichage court alors qu'il n'est pas dans la grille de base
  - le champ `othertitle` figure dans l'affichage court alors qu'il n'est pas dans la grille de base

- type `report` (rapport) : 
  - le champ `othertitle` figure dans l'affichage court alors qu'il n'est pas dans la grille de base

**Comment by daniel-menard** [comment]
Le bug est maintenant corrigé dans le code source de docalist. Cela évitera que les bases qui seront créées à l'avenir aient le même problème : 

- suppression de `event` dans le formulaire de saisie du type `meeting`.
- suppression de `othertitle` dans l'affichage court des types `meeting`, `periodical-issue` et `report`
- suppression de `author` dans l'affichage court du type `periodical-issue`

**Comment by daniel-menard** [comment]
J'ai modifié manuellement les paramètres des bases de données sur le .net et le .org pour corriger les bases existantes (types `meeting`, `periodical-issue` et `report`) : 

- sur le .net, correction de la base "tests de saisie" et de la base "prisme"
- sur le .org, correction de la base "tests de saisie" et de la base "prisme"

Je pense que ce ticket peut désormais être fermé, mais merci de tester.

@Nicolas-L : 
> Après vérification, cela concerne les types de notices suivantes :  
> - Sur le .ORG : **Législation** / Congrès colloque / Numéro de périodique / Rapport colloque
> - Sur le .NET : Congrès colloque / Numéro de périodique / Rapport

Je n'ai pas vu de soucis particulier pour le type `legislation`sur le .org. Pouvez-vous re-tester ?

**Comment by Nicolas-L** [comment]
Test `Legislation` sur .ORG : OK
