### ISSUE TITLE
Différence .NET/.ORG

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#308]
L'identifiant de la base Prisme est différent entre les deux sites
.NET : base/prisme
.ORG : base-prisme

Normal ?

**Comment by daniel-menard** [comment]
Lorsque j'ai refait le site .net avec le nouveau système de bases (possibilité d'indiquer a page d'accueil de chaque base, etc.), j'ai choisi de publier la base Prisme en dessous de la page Bases.

Cela semble logique de faire ça car ça permet de créer une arborescence : /Bases/Prisme, /Bases/Revues, etc.

Mon idée première était de faire la même chose pour le .org, mais au moment de publier je me suis rendu compte qu'on allait "casser" tout le référencement google existant si on changeait l'adresse de la base de façon sauvage (il y a tout de même [près de 65000 notices indexées](https://www.google.com/webhp?q=site%3Adocumentation-sociale.org%2Fbase-prisme%2F) !)

Je suis donc revenu en arrière et j'ai conservé pour le .org l'adresse d'origine de la base (/base-prisme).

On pourra éventuellement changer les choses par la suite, mais c'est un projet en soi car il faut mettre en place un système de redirection de l'ancienne adresse vers la nouvelle.

**Comment by Nicolas-L** [comment]
Avis personnel : 

C'est une sage précaution mais à vrai dire, cela ne me dérangerait pas plus que ça de de faire tomber le référencement pour quelques mois - s'il ne s'agit "que" de ça - étant donné que nous ne courrons pas après le nombre de connexions pour ce site.

J'aurais presque préféré que les choses soient d'équerre et qu'on règle le sujet une bonne fois pour toute - franc du collier - plutôt que de remettre ça à un autre projet.

Après, c'est vrai que ça ne fait pas très "permalien" pour ceux qui auraient fait des renvois directs sur nos notices, mais nous n'avons pas pris d'engagement de la sorte. Nous pourrions a minima faire une info pour les membres de Prisme le cas échéant, voire créer une page d'info sur le site dont l'url se terminerait par `/base-prisme/` et qui récupérerait toutes les requêtes vers les "anciennes" url de notices.

Avis personnel...

**Comment by ocormont** [comment]
Je suis du même avis que Nicolas
