### ISSUE TITLE
Import de notices sans le numéro REF

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#309]
Dans les options d'import il faudrait pouvoir ne pas tenir compte du numéro REF. Ceci afin de ne pas créer plusieurs notices avec le même numéro.

Question à part : est-ce que cette information propre à la base Prisme qui a un lien "historique" en tant qu'identifiant doit nécessairement être confondue avec le numéro identifiant de la notice une fois importée dans Docalist ?

**Comment by daniel-menard** [comment]
Fait : lors de l'import, on a maintenant une option qui permet d'indiquer si on souhaite ou non importer le numéro de ref éventuel qui figurent dans les notices du fichier.

Comme on commence à avoir plusieurs options lors de l'import, j'en ai profité pour revoir la façon dont elles sont présentées à l'écran et ajouter des notes de description : 

![image](https://cloud.githubusercontent.com/assets/3940667/9518667/e17044aa-4cb8-11e5-9704-cb3696abbfe5.png)

Pour mémoire, l'écran se présentait comme ça auparavant : 

![image](https://cloud.githubusercontent.com/assets/3940667/9518617/45c1ddac-4cb8-11e5-8d4a-c5c54ba59ada.png)

Pour le moment, c'est déployé uniquement sur le .net : merci de tester et me dire si tout fonctionne et je ferai ensuite la mise à jour sur le .org.

**Comment by Nicolas-L** [comment]
J'ai testé, ça fonctionne ! RAS pour moi.

**Comment by daniel-menard** [comment]
OK, c'est déployé sur le .org.
