### ISSUE TITLE
Remarque : Mode d'affichage des notices dans le back office

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#310]
Dans le back, il y a une différence d'affichage entre les notices au statut "En attente" et celles qui sont validées quand on active l'option :  ![capture0](https://cloud.githubusercontent.com/assets/5398758/8476655/bd808058-20c3-11e5-9094-87a297fdbe99.JPG)

Seules les notices "En attente" sont affichées avec plus de détails

![capture2](https://cloud.githubusercontent.com/assets/5398758/8476679/eac0fa20-20c3-11e5-85be-5d8b61622f96.JPG)

Les notices validées restent en affichage simple

![capture1](https://cloud.githubusercontent.com/assets/5398758/8476686/f63e1cfc-20c3-11e5-82b8-7772854e82b7.JPG)

**Comment by daniel-menard** [comment]
**Ce bug est désormais corrigé.**

Initialement, je pensais que c'était juste un problème d'affichage, mais c'était lié à la gestion des droits d'accès.

En fait, il faut bien comprendre que l'icone "détail" ne se contente pas d'afficher de façon systématique le résumé de toutes les notices : elle tient compte des droits d'accès de l'utilisateur en cours : 

- Un utilisateur qui a uniquement les droits "auteur" sur la base verra uniquement le résumé des notices auxquelles il a accès : notices publiques (en statut publié) et notices en attente ou en brouillon mais dont il est l'auteur. Pour les autres notices (brouillons et notices en attente saisies par un autre utilisateur), aucun résumé ne sera affiché.

- Par contre, un éditeur ou un administrateur de la base verra le résumé de toutes les notices quels que soient leur statut et leur auteur puisqu'il dispose des droits requis.

Dans le code de docalist, il y avait une erreur qui provoquait le problème d'affichage : on demandait un droit qui n'existait pas (bug introduit dans le ticket #249, lorsqu'on a travaillé sur la gestion des droits d'accès).

C'est désormais corrigé et on a maintenant sur le .net et le .org le comportement correct décrit ci-dessus.
