### ISSUE TITLE
Back office pas "responsive"

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#313]
La liste des notices de la base dans le back office de WP n'est pas responsive (contrairement aux articles, pages...).

**Comment by Nicolas-L** [comment]
Par ailleurs, il faudrait désactiver l'option reponsive pour le front.

**Comment by daniel-menard** [comment]
> La liste des notices de la base dans le back office de WP n'est pas responsive (contrairement aux articles, pages...).

Jusqu'à récemment, les "listes de posts" wordpress n'étaient pas spécialement responsives : pour les articles et les pages, cela s'affichait à peu près bien car wp avait des styles exprès pour ça, mais avec les colonnes qu'on ajoute dans l'écran "liste des notices", cela ne fonctionne plus.

Dans WordPress 4.3 (qui vient juste de sortir), [un gros travail a justement été fait](https://make.wordpress.org/core/2015/08/08/list-table-changes-in-4-3/) pour améliorer les listes de posts et les rendre réellement responsives. Désormais, sur un petit écran, seule la colonne principale est affichée et on a un "touch button" qui permet d'ouvrir les posts pour voir le contenu des colonnes masquées : 

![](https://make.wordpress.org/core/files/2015/08/list-tables-43.gif)

Je viens d'installer wp 4.3 sur mon poste local pour voir ce que ça pourrait donner pour nos listes de notices. Ce n'est pas très concluant : 

![image](https://cloud.githubusercontent.com/assets/3940667/9386760/59895910-475d-11e5-95d2-28cdf1de5e0d.png)

En fait, les améliorations apportées à WP 4.3 ne fonctionnent que si c'est la première colonne qui est désignée comme colonne principale (celle qui contient les actions comme modifier - corbeille - afficher).

Or, actuellement, dans nos listes de notices, ce n'est pas le cas : on affiche ref, type, puis seulement la colonne titre qui est la colonne principale : 

![image](https://cloud.githubusercontent.com/assets/3940667/9386824/a7fe1fcc-475d-11e5-833f-21eb398a8983.png)

Le ticket [wp#33308](https://core.trac.wordpress.org/ticket/33308) explique le problème mais laisse peu d'espoir que ce soit résolu un jour (il se peut même que wp *impose* un jour que la première colonne soit la colonne principale).

Partant de là, ça nous donne deux possibilités.

**1. On désigne la colonne ref (la première) comme colonne principale**

Techniquement ça marche, mais le rendu est inacceptable car la colonne n'est pas assez large et du coup les actions s'empilent : 

![image](https://cloud.githubusercontent.com/assets/3940667/9387687/0e909f18-4762-11e5-8502-b0b898442ace.png)

Même si on agrandit la colonne, ça reste moyen : 

![image](https://cloud.githubusercontent.com/assets/3940667/9387745/4cf556d6-4762-11e5-8edf-cd433b377fe4.png)

**2. On change l'ordre des colonnes**

Dans cette hypothèse, le titre redevient la première colonne (comme pour les articles et les pages), et ensuite seulement on aurait ref et type : 

![image](https://cloud.githubusercontent.com/assets/3940667/9386969/72d7d38c-475e-11e5-91f5-a4b8708e3612.png)

Si on fait ça, ça marche aussi sur petit écran avec wp 4.3 : 

![image](https://cloud.githubusercontent.com/assets/3940667/9387047/d1591916-475e-11e5-967a-e10f446bd3a7.png)

Dans ces conditions, ça me semble être la seule solution. Après, je trouve que ça fait bizarre d'avoir ref et type après le titre, mais peut-est-ce uniquement parce que je suis habitué comme ça ?

Qu'en pensez-vous ? On fait ça ? Vous voyez-vous d'autres solutions ?


> Par ailleurs, il faudrait désactiver l'option reponsive pour le front.

Je n'ai pas bien compris ce qui n'allait pas (sachant que le thème 2012 n'est *pas du tout* responsive...) Pouvez-vous faire un ticket séparé et expliquer ce qu'il faudrait faire, svp ?

**Comment by Nicolas-L** [comment]
Pour moi, rien de choquant, si ce n'est que j'aurais du coup plutôt placé la colonne Ref après Type.

En effet, la Réf est une info de gestion alors que le titre et le type renseignent sur la nature du document.
Dans l'ordre : 1.Titre, 2.Type, 3. Réf, etc.

Mais c'est purement subjectif... en tout cas l'option 2 me semble convenir.

**Comment by daniel-menard** [comment]
Fait.

**Comment by Nicolas-L** [comment]
Juste deux remarques : 

1ère : 

- En dépliant les champs sur petit écran, la colonne Réf est décalée

![capture1](https://cloud.githubusercontent.com/assets/5398758/9435087/deaee832-4a44-11e5-8b5a-fa5962733bdc.JPG)

2ème : 

- Sur - très - grand écran, l'espace entre le titre est la colonne type est très important

![capture2](https://cloud.githubusercontent.com/assets/5398758/9435105/1b3234c6-4a45-11e5-9119-2e1e48609e53.JPG)
