### ISSUE TITLE
ES : Message d'erreur quand on ne ferme pas les guillemets

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#314]
Gros message d'erreur qui prend toute la page quand on oubli de fermer les guillemets dans une requête.

Ex : 
![image](https://cloud.githubusercontent.com/assets/5398758/8545672/1bfc6b38-24b1-11e5-801e-f7e2949ba4f2.png)

Voir : http://www.documentation-sociale.org/recherche/?q="test

**Comment by ocormont** [comment]
Même message lorsque la requête est incompréhensible par le moteur

**Comment by daniel-menard** [comment]
**C'est corrigé :**

- Le plugin docalist-search a été modifié pour qu'on ne génère plus d'exception lorsque la requête exécutée contient une erreur. A la place, on a maintenant un flag qui nous indique si tout s'est bien passé ou non.

- De son côté, le thème Prisme a été modifié pour tenir compte de ce flag. Si une erreur est survenue, on affiche désormais un message explicite "Erreur dans votre requête".

  On affiche toujours le message d'erreur retourné par ElasticSearch (car cela peut aider à comprendre où est le problème, même si celui-ci est en anglais), mais sous une forme très simplifiée.

- Enfin, les modules facettes et export panier ont été adaptés pour tenir compte du fait qu'on peut désormais n'avoir aucun résultat pour la requête en cours.

Au final, on obtient, en cas d'erreur, une page un peu plus avenante que ce qu'on avait avant : 

![image](https://cloud.githubusercontent.com/assets/3940667/9561352/baff6820-4e41-11e5-86dd-677c945d727b.png)

Pour mémoire, voila la page qu'on obtenait avant ces modifications... : 
![image](https://cloud.githubusercontent.com/assets/3940667/9561319/80dcf4a6-4e40-11e5-95a8-3536b53c2506.png)
