### ISSUE TITLE
Export Prisme : champ URL

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#316]
Le format 2011 (test avec format riche) contient l'url ainsi que la date de consultation du site.
A l'export, nous avons http://www.documentation-sociale.org/(20150709)

Il faut mettre un espace entre Url et (AAAAMMJJ)

Pour la date, est-il possible de la transformer en (page consultée le JJ-MM-AAAA) ?

**Comment by daniel-menard** [comment]
Le ticket reseau-prisme/site/issues/19 remplace ce ticket. Finalement, la date de consultation a été supprimée du champ URL dans le format Prisme2011.
