### ISSUE TITLE
Système des requêtes hebdomadaires

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#322]
Après usage de la méthode "repérage du dernier numéro" pour faire la requête REF[xxx TO yyy], on voit que cela n'est pas fiable.

Les numéros sont listés de manière désordonnés suivant l'ordre de correction.
D'une semaine sur l'autre des numéros se chevauchent et la logique de la requête n'est plus suffisante pour exclure les notices qui ont déjà fait partie de la semaine précédente.

Le problème étant que les notices en attente sont quand même numérotées. Du coup si une notice en attente se retrouve entre deux notices publiées, elle ne sera pas prise en compte dans la requête de la prochaine semaine qui partira de la dernière notice publiée + 1

**Exemple fictifs avec notre méthode actuelle** (je rajoute à la requête "status:publie" pour écarter les notices en attente qui apparaissent sur mon compte admin) **:**

*Semaine 1*
1. Les notices [01 à 20] sont créées
2. Les notices [05 à 10] et de [15 à 20] sont corrigées
=> ma requête sera "ref[01 TO 20] status:publie"

*Semaine 2*
1. les notices [21 à 35] sont créées
2. Les notices [01 à 04] et [11 à 14] et de [25 à 30] sont corrigées
=> ma requête sera "ref:[21 TO 30] status:publie"

- Les notices [01 à 04] et [11 à 14] ne seront pas comprises dans la requête de la semaine 2
- Si je les comprends dans la prochaine requête - en suivant l'"ordre" d'apparition dans la liste - la requête incluera des notices de la semaine précédente. Ex : semaine 2 : ref:[01 TO 30] => et je me retrouve avec les notices de la semaine 1.

Pour que notre système fonctionne il faudrait que les correcteurs corrigent en respectant strictement l'ordre de création des notices. Or ceci n'est pas réellement envisageable car ils se partagent les revues.

**Comment by Nicolas-L** [comment]
Il faudrait que le numéro des notices soient créés lors du passage en statut "Validé".

Cela permettrait : 
- d'avoir une file de notices ne contenant aucune notice "en attente" entre deux notices validées.
- que les équations "ref[xx TO yy]" ne contiennent strictement que des notices validées pendant la semaine
- que les équations "ref[xx TO yy]" laissent de côté les notices "en attente" pour l'équation de la semaine de leur publication (correction) effective, et non celle de leur création effective.

**Comment by daniel-menard** [comment]
Fait : désormais, on n'attribue un numéro de ref aux notices que lorsqu'elles sont en statut `publish`.

**Comment by Nicolas-L** [comment]
Juste deux remarques : 

1ère : 

- En dépliant les champs sur petit écran, la colonne Réf est décalée

![capture1](https://cloud.githubusercontent.com/assets/5398758/9435087/deaee832-4a44-11e5-8b5a-fa5962733bdc.JPG)

2ème : 

- Sur - très - grand écran, l'espace entre le titre est la colonne type est très important

![capture2](https://cloud.githubusercontent.com/assets/5398758/9435105/1b3234c6-4a45-11e5-9119-2e1e48609e53.JPG)
