### ISSUE TITLE
Table prisme-media-degree

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#323]
@ocormont : La table prisme-media-degree est appliquée pour la grille Article.
- Il faudrait en faire une spécifique "Article" qui comprenne aussi les CDRom et la mettre à la place de celle qui sert pour les notices Diplôme

**Comment by Nicolas-L** [comment]
Ou alors qu'on fasse le "deuil" de ces trois petites notices CDRom et qu'on ne remplisse pas le champ Support.

**Comment by Nicolas-L** [comment]
@daniel-menard : En voulant ajouter à la table la valeur CDRom (que j'ai maintenant retiré), j'ai remarqué que la facette affichait le code et non le label (DB au lieu de CDRom).

![capture](https://cloud.githubusercontent.com/assets/5398758/8928279/904f876e-351d-11e5-97ce-d40ef0795400.JPG)

Le champ "Support du document" affiche bien le label sur les notices une fois déployées

Est-ce qu'il y a, dans ce cas, un cache à vider depuis le back office pour que les facettes se mettent à jour en fonction des tables ?

**Comment by ocormont** [comment]
J'ai activé la table prisme-media pour la grille Article. Le DB apparaissait quand même.
En modifiant les 3 notices (supression et rajout du support), cela fonctionne.

En activant cette table, nous avons un choix plus important de support pour la grille, mais comme nous étions parti du principe de limiter le nombre de table...
Je ferme ce ticket

**Comment by Nicolas-L** [comment]
This issue was moved to reseau-prisme/site#14
