### ISSUE TITLE
Listes dans la recherche avancée

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#325]
Je me suis "amusé" à passer un nom d'auteur en minuscules (et supprimer son Majuscule) et à corriger une référence de revue qui n'était pas appropriée.

En recherche avancée, j'ai remarqué que, si on avait éliminé complètement des références de la base, certaines d'entre elles persistent et d'autres s'"effacent" des listes : Quand on interroge la recherche avancée, des informations restent proposées dans les listes et d'autres finissent par ne plus apparaître.

Ex : J'ai transformé un nom d'auteur dans la base : `NOM Prénom` et `NOM P.` => `Nom Prénom`
- `NOM P.` n'est plus présenté
-  `NOM Prénom` est toujours présenté alors qu'il ne renvoie à aucune référence après cette correction

Pour la référence de revue, au début le nom supprimé était proposé, puis quelques jours plus tard il n'y était plus. (Pas instantané)

Y-a-t-il une manip pour mettre à jour ces listes de manière plus instantanée ?

**Comment by daniel-menard** [comment]
Les listes affichées dans les lookups (que ce soit dans le formulaire de recherche avancée ou dans le formulaire de saisie/modification de notice) sont générées via des requêtes ajax qui sont mises en cache par le navigateur.

Cette mise en cache est nécessaire pour éviter que le formulaire de saisie ne mette trop longtemps à charger et pour limiter la charge sur le serveur.

- pour les lookups sur index, le délai de mise en cache est de 10 minutes
- pour les lookups qui portent sur des tables, le délai de mise en cache est d'une semaine (l'hypothèse, c'est que les tables ne change pas tous les jours)

Quand on fait des corrections sur les index, on peut donc effectivement avoir dans la liste des entrées qui n'existent plus et il faut attendre 10 minutes pour que la liste s'actualise (je reconnais que ce n'est pas idéal).

> Y-a-t-il une manip pour mettre à jour ces listes de manière plus instantanée ?

La seule solution consiste à vider le cache du navigateur (totalement ou en partie, par exemple seulement la dernière heure) pour le forcer à charger une version "à jour" des tables depuis le serveur.
