### ISSUE TITLE
Saisie des noms d'auteurs

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#327]
***Deux questions :***

- *Espace(s) en fin de champ :*

J'ai remarqué que des producteurs saisissent le nom d'un auteur et - sans doute par mauvais réflexe - mettent 1 voire 2 espaces après l'information (Nom[espace][espace]).
Ceci pose plusieurs désagréments : à l'affichage sur le site où la ponctuation se trouve décalée, à l'export, et ceci démultiplie les doublons.

*Au moment de la validation de la notice, serait-il possible de ne pas tenir compte de ces espaces en fin de champ ?*

- *Saisie des tirets :*

Dans les recommandations (ou habitude ?) "anciennes" de saisie des noms et prénoms d'auteurs, les producteurs ne saisisent pas les tirets [-], notamment pour les prénoms composés (ex : Jean-Pierre => Jean Pierre).
Il ne me semble pas qu'il y ait aujourd'hui de contre indication à saisir ce tiret.

*Est-ce que nous pouvons mettre à jour cette recommandation ?*

**Comment by daniel-menard** [comment]
> Espace(s) en fin de champ

**Fait.**

En fait, le problème est valable pour tous les champs et sous-champs de la notice : de manière générale, les espaces de début et de fin ne sont pas significatifs et n'ont pas lieu d'être conservés.

C'est le cas également des caractères tabulations ou retour chariot de début ou de fin (résumé par exemple).

Je viens de publier une nouvelle version qui supprime les blancs (` \t\n\r\0\x0B`) de début et de fin dans tous les champs lorsque la notice est enregistrée.

Pour les notices déjà saisies, je ne vois pas de manière simple de corriger : il faudrait les passer en revue et corriger manuellement. Cela ne concerne que les notices saisies en ligne depuis l'ouverture car pour les notices importées, les espaces superflus dans les auteurs sont déjà supprimés par le programme d'import.

> Saisie des tirets - mettre à jour la recommandation

La saisie (ou non) des traits d'union ne devrait pas poser de problème. Par contre, il faut que ce soit homogène : dans les index d'aide à la saisie et dans les facettes, `Jean-Pierre` et `Jean Pierre` seront considérées comme deux valeurs différentes.
