### ISSUE TITLE
Taille du formulaire de recherche

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#328]
Serait-il possible d'agrandir la taille du formulaire de recherche ?

![capture](https://cloud.githubusercontent.com/assets/5398758/9134548/7d3b41dc-3d05-11e5-9e15-6240c39db22f.JPG)

**Comment by daniel-menard** [comment]
J'ai un peu agrandi la taille de la zone de texte : 

![image](https://cloud.githubusercontent.com/assets/3940667/9554083/a68eb1bc-4dc3-11e5-80f1-269d97a79cad.png)

J'aurais souhaité que la zone fasse toute la largeur (100%), mais ce n'est pas possible avec le thème prisme actuel car il utilise une vieille version de twitter bootstrap qui ne permet pas de faire ça.
