### ISSUE TITLE
Requête avec ":" dans le titre

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#332]
Lorsqu'on recherche un titre comportant `:` dans le titre, la notice ne sort pas.

Ex : `Famille et corps : identité et transmission` (notice n° : 78922).

**Comment by daniel-menard** [comment]
Dans la [syntaxe de recherche ElasticSearch](https://github.com/docalist/docalist/wiki/Syntaxe-des-requ%C3%AAtes#fields), le caractère `:` sert à faire une recherche sur un champ (et ce même s'il y a un espace avant et/ou après).

Dans l'exemple donné, ElasticSearch comprend qu'on veut rechercher le mot `identité` dans le champ `corps` (et `famille` et `transmission` dans n'importe quel champ). Comme le champ `corps` n'existe pas, on obtient zéro réponse.

Pour faire la recherche souhaitée (recherche par titre exact), il faut neutraliser le caractère `:` : 

- le plus simple consiste à faire une recherche par phrase : 
  
  [`"Famille et corps : identité et transmission"`](http://www.documentation-sociale.org/base-prisme/recherche/?q=%22Famille+et+corps+%3A+identit%C3%A9+et+transmission%22)

- on peut aussi le supprimer manuellement : 
  
  [`Famille et corps identité et transmission`](http://www.documentation-sociale.org/base-prisme/recherche/?q=Famille+et+corps+identit%C3%A9+et+transmission)

- on bien encore utiliser un antislash (`\`) pour neutraliser le caractère gênant : 
  
  [`Famille et corps \: identité et transmission`](http://www.documentation-sociale.org/base-prisme/recherche/?q=Famille+et+corps+%5C%3A+identit%C3%A9+et+transmission)

Dans les deux cas, on obtient bien la notice recherchée parmi les réponses obtenues.
