### ISSUE TITLE
Liens incorrects sur le site .org

### ISSUE THREAD

**Issue by daniel-menard** [docalist/docalist#333]
J'ai repéré deux pages du site .org qui ont des liens incorrects : 

1. [Base Thesis](http://www.documentation-sociale.org/prisme/produits-services/base-thesis/)

  Cette page contient des liens vers le site .net. Ces liens sont de fait rompus puisque l'accès au .net est protégé. Cela concerne les liens suivants : 
  - Communiqué de presse de septembre 2011 (pdf)
  - Programme de la journée (pdf)
  - Intervention (diaporama)
  - Publication

2. [Regard(s) Social](http://www.documentation-sociale.org/ressources/regards-social/)

  Le lien "consulter les références" n'est plus valide (c'était l'ancien système de recherche).

**Comment by Nicolas-L** [comment]
C'est corrigé
