### ISSUE TITLE
Importer seulement les x premières notices d'un fichier

### ISSUE THREAD

**Issue by daniel-menard** [docalist/docalist#339]
Pour faire des tests d'import ou valider qu'un fichier a le bon format, ce serait pratique d'avoir une option permettant de n'importer que les *n* premières notices du fichier.

**Comment by daniel-menard** [comment]
Fait, on a maintenant une nouvelle option lors de l'import qui permet de limiter le nombre de notices importées : 

![image](https://cloud.githubusercontent.com/assets/3940667/9518983/6bf28e24-4cbb-11e5-8899-54a5f0efde67.png)

**Comment by Nicolas-L** [comment]
Juste une toute petite remarque sur l'ordre des options d'import : 

Dans ma logique toute personnelle, j'aurais plus vu "Limite de l'import" placée en dessous (ou proche) de l'option "Simuler l'import"

**Comment by daniel-menard** [comment]
C'est fait :-)
