### ISSUE TITLE
Sélection de notices sur une page

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#342]
Je trouve que le module de sélection des notices est un peu confusant sur la question de la sélection des 10 notices d'une page.

![capture2](https://cloud.githubusercontent.com/assets/5398758/9542295/ca2b0e30-4d6f-11e5-990c-c34b3bd3502f.JPG)

C'est une option un peu "bonus" qui perturbe sous cette forme peu intuitive (avis personnel recoupé avec le retour d'expérience #341)

Sur internet, on a plutôt l'habitude de "cocher / décocher" avec le nombre de notices indiqué et éventuellement une icone "panier". Le tout placé au dessus de la liste et non sur une side bar.

Ex :  

![capture](https://cloud.githubusercontent.com/assets/5398758/9542167/b594effa-4d6e-11e5-9392-9670389626d0.JPG)

ou

![capture1](https://cloud.githubusercontent.com/assets/5398758/9542185/d9350cb0-4d6e-11e5-8f40-87e45a62990f.JPG)

Personnellement, en l'état, je préférerais que l'option (Ajouter tout / Enlever la page) soit désactivée sur le .ORG pendant le temps de la prise en main par le réseau.

**Comment by daniel-menard** [comment]
En attendant qu'une V2 du module de gestion du panier soit développé, vous pouvez supprimer les liens "ajouter tout" et "enlever tout" en paramétrant le widget panier : il suffit de supprimer le libellé des liens et ceux-ci n’apparaîtrons plus : 

![image](https://cloud.githubusercontent.com/assets/3940667/9852797/7a5212e8-5b00-11e5-856d-4a18eb56afe4.png)

(remarque : à faire pour toutes les pages qui utilisent un widget panier).

**Comment by Nicolas-L** [comment]
OK, je fais ça pour le .ORG pour l'instant. On verra quand le réseau sera demandeur de plus d'options sur le panier.
