### ISSUE TITLE
Institution du producteur

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#353]
**Question :**

- qu'est-ce qui détermine l'institution du producteur ? dans quel champ est renseignée cette information ?

![capture](https://cloud.githubusercontent.com/assets/5398758/9761104/d76cea70-56fa-11e5-9c38-c75e00693ff7.JPG)

**Comment by ocormont** [comment]
Il s'agit du champ OP qui se trouve dans le bloc information de gestion.
En vérifiant, c'est un champ visible seulement par les utilisateurs ayant le rôle membre.prisme.
En tant qu'administrateur, nous devrions voir ce champ, ce qui n'est pas le cas.
J'ai voulu ajouter à mon compte admin ce rôle secondaire mais je n'ai pas réussi. Trou de mémoire ou autre

**Comment by Nicolas-L** [comment]
Ça me fait penser au #307 (deuxième post)

**Comment by Nicolas-L** [comment]
Je ferme ce ticket car nous avons poursuivi la problématique évoquée par Olivier sur https://github.com/reseau-prisme/site/issues/15
