### ISSUE TITLE
status:"en attente"

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#356]
Suite au ticket #322,

**Remarque :** L'équation `ref:0` ne donne aucun résultat, `status:"en attente"` non plus...

Du coup je me demande si les notices pas encore validées ou en brouillon sont visibles en front par leurs producteurs comme nous l'avions annoncé. Et j'ai bien peur que non.

Ceci est surtout utile pour que les producteurs n'aient pas à attendre la correction de leurs propres notices pour les importer dans leurs bases locales.

**Comment by Nicolas-L** [comment]
Je ferme, contrairement à ce que je viens de dire status:"en attente" fonctionne très bien.
Fausse alerte

**Comment by daniel-menard** [comment]
J'étais en train de tester de mon côté mais vous m'avez devancé !

Donc effectivement, la requête `status:"en attente"` fonctionne.

Pour ce qui est de "ref:0", cela ne fonctionne pas, car en fait si la notice n'a pas de numéro de référence (i.e.), le champ est supprimé lors de l'enregistrement et du coup, le champ n'est pas indexé par ES.

Par contre, ES dispose d'une syntaxe qui permet de rechercher les notices qui ne contiennent pas un champ donné en utilisant le pseudo-champ `_missing_` (avec un underscore avant et après). On peut ainsi faire une requête de la forme [`_missing_:ref`](http://www.documentation-sociale.org/base-prisme/recherche/?q=_missing_%3Aref) et on obtient toutes les notices qui n'ont pas de champ ref (et donc, dans notre cas, qui n'ont pas encore été publiées).

Ce genre de requête peut être très utile pour faire de la détection d'erreurs : [notices sans mots-clés](http://www.documentation-sociale.org/base-prisme/recherche/?q=_missing_%3Atopic) (5 réponses), [articles sans titre de périodique](http://www.documentation-sociale.org/base-prisme/recherche/?q=type%3Aarticle+_missing_%3Ajournal) (3 notices), etc.

Inversement, on peut rechercher les notices qui contiennent un champ en utilisant le pseudo-champ `_exists_` (idem, un underscore avant et après). Par exemple, l'inverse de la recherche "ref:0" serait [`_exists_:ref`](http://www.documentation-sociale.org/base-prisme/recherche/?q=_exists_%3Aref). 

Là encore, pour de la détection d'erreurs, ça peut être utile. Par exemple, les notices qui ne sont pas des articles mais pour lesquelles on a un champ journal renseigné : [`-type:article _exists_:journal`](http://www.documentation-sociale.org/base-prisme/recherche/?q=-type%3Aarticle+%2B_exists_%3Ajournal) (2 réponses), etc.

**Comment by daniel-menard** [comment]
Autre chose, ça pourrait être utile d'ajouter la facette `statut` dans la liste des facettes affichées car cela permettrait aux utilisateurs de simplement cliquer sur "En attente" : 

![image](https://cloud.githubusercontent.com/assets/3940667/9930856/1928a174-5d37-11e5-9a63-fbb410dbda40.png)

Remarque : tant que le bug #307 n'est pas résolu, il faudra l'afficher pour tout le monde, mais les gens qui n'ont pas les droits (simple visiteur par exemple) verront uniquement l'entrée "Publiée" :
 
![image](https://cloud.githubusercontent.com/assets/3940667/9930844/06680dcc-5d37-11e5-9159-af72423cd8a9.png)
