### ISSUE TITLE
Requête sur vocabulaire spécifique

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#368]
Est-il possible de générer une équation pour faire une recherche sur un terme spécifique à un thésaurus précis ?

En effet, dans notre liste de Domaines, des termes sont synonymes à d'autres qui appartiennent au thésaurus Prisme. Ex : Éducation, Handicap, Santé...

Pour reprendre cet exemple, je souhaiterais faire une requête sur le terme *Éducation*, **uniquement** le terme issu du thésaurus *Domaine* - et non celui du thésaurus *Prisme*.

C'est un point important pour la base *Site web* par exemple où l'on veut faire des recherches par grands domaines, autant pour les producteurs (responsable d'un domaine précis) que pour les utilisateurs.

PS : Je pense - **a posteriori** - qu'il ne faut pas mixer Catégorisation et Indexation. Les domaines, c'est finalement *un peu* à prendre comme des cotes.

**Comment by daniel-menard** [comment]
*Je répond rapidement pour que vous ne soyez pas bloqués dans votre réflexion.*

Le champ mots-clés (`topic`) est un "multi-champs". Pour presque tous les multi-champs, on a à la fois un index général qui recherche sur toutes les entrées et un index spécifique (un par type d'entrée) qui permet de ne rechercher que sur les entrées d'un type donné.

Pour la base prisme (par exemple), on peut donc interroger sur tous les types de mots-clés avec une équation de la forme [`topic:éducation`](http://www.documentation-sociale.org/base-prisme/recherche/?q=topic%3A%C3%A9ducation) (4955 réponses) et interroger sur un type de mots-clés particulier avec une équation de la forme [`topic.domaines:éducation`](http://www.documentation-sociale.org/base-prisme/recherche/?q=topic.domaines%3A%C3%A9ducation) (26 réponses).

De la même façon, on pourrait interroger spécifiquement sur `topic.prisme`, `topic.names`, `topic.geo`, `topic.period`, `topic.tag` et `topic.free`, c'est-à-dire toutes les entrées qui composent la table `prisme-topics` : 

![image](https://cloud.githubusercontent.com/assets/3940667/12143699/1c1d1088-b483-11e5-8d61-cf531f589d57.png)

C'est vrai également pour d'autres champs multifield comme `number` : une requête de la forme `number:xxx` recherchera sur tous les types de numéros, `number.isbn` ne recherchera que sur l'isbn, `number.doi`que sur le DOI, etc.

*Remarque :* pour mes exemples, j'ai pris la base prisme plutôt que la base web (comme les notices ne sont pas encore publiées), mais cela fonctionne pareil. Il faut juste adapter, s'il y a lieu, le nom des index en fonctions de la table d'autorité utilisée.

En espérant que cela vous aide !

---

> PS : Je pense - a posteriori - qu'il ne faut pas mixer Catégorisation et Indexation. Les domaines, c'est finalement un peu à prendre comme des cotes.

Je comprend bien la réserve d'un point de vue "métier", mais d'un point de vue technique, c'est vraiment similaire : un moyen de créer des [classes d'équivalences](https://fr.wikipedia.org/wiki/Relation_d%27%C3%A9quivalence) au sein d'un ensemble de notices. 

Et rien ne dit qu'on ne gérera pas les cotes comme un cas particulier de topic le jour où on gérera des cotes :-)

Il me semble que c'est plus en terme d'interface utilisateur que c'est gênant. Mais lorsqu'on pourra gérer des "vues éclatées" pour les formulaires (comme on le fait déjà pour les affichages), je pense que ce sera moins problématique.
