### ISSUE TITLE
Facette Revue de la bdd Audiovisuelle

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#371]
Quand on va sur la [bdd Audio](http://www.documentation-sociale.org/base-audiovisuel/recherche/?q=%2A) du site de Prisme (il faut être connecté), on a une facette Revue - ? - qui apparaît et qui donne des infos qui n'ont rien à voir avec des publications et que je ne retrouve pas dans les notices.

![capture](https://cloud.githubusercontent.com/assets/5398758/14891765/573d181e-0d68-11e6-8e48-fd2172b3b4cd.JPG)

**Comment by ocormont** [comment]
C'est à cause de moi.
J'ai fait un import de notices audiovisuelles. J'ai adapté les champs en fonction de l'import Docalist et j'ai mis des infos dans le champ TP afin de pouvoir faire des copier coller par la suite.
Cependant, je n'ai pas pensé que ce champ n'existait pas dans les notices films.
Je m'en occupe...

**Comment by Nicolas-L** [comment]
This issue was moved to reseau-prisme/site#44

**Comment by ocormont** [comment]
C'est réparé.
Suite à mon erreur :
- Si un import est effectué avec des champs renseignés qui n'existe pas dans la grille notice voulue, c'est champs sont importés, indexés, mais on ne peut pas les voir et modifier.
