### ISSUE TITLE
Champ des notices : remise à zéro des valeurs par défaut

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#373]
Il est possible de paramétrer des valeurs par défaut aux champs des différents types de notices.
Cependant, il n'est pas possible de remettre ce champ avec aucune valeurs par défauts.

![capture](https://cloud.githubusercontent.com/assets/5398792/16381057/eb98c51c-3c7a-11e6-8466-5349ab43889c.JPG)

Je voulais enlever le champ Note de la grille de saisie Site web afin de ne laisser que Résumé.
Cela n'est pas possible. 
J'ai tenté de détourner en créant une table content ne contenant que le champ Résumé. Je l'ai activé dans la Grille de Base. En retournant dans le paramétrage de la grille de saisie, le champ note est toujours présent avec comme valeur "Invalide". J'ai tout remis comme initialement.
(Idem avec tag dans Indexation : reseau-prisme/site#38)

J'ai besoin de remettre à zéro plusieurs champs de la notice Site Web.

**Comment by daniel-menard** [comment]
Je viens de faire un test sur le .net : on peut supprimer une valeur par défaut, mais ce n'est pas très intuitif : il faut cliquer sur le menu déroulant (le select qui affiche "Note") pour qu'il ait le focus (on a un curseur clignotant) puis taper sur la touche "Retour arrière" du clavier (backspace).

Ensuite, lorsque la grille est enregistrée, docalist détecte que les deux attributs (type et valeur) de cette valeur par défaut sont vides et il la supprime.

**Comment by ocormont** [comment]
Ca marche, merci
