### ISSUE TITLE
Chercher Remplacer : Modification impossible

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#377]
http://www.documentation-sociale.net/recherche/?q=*&topic-prisme-hierarchy=ACTION%20%20HUMANITAIRE
Impossible de modifier via le chercher remplacer le mot clé Action Humanitaire, que ce soit en topiv.value ou en topic/type.prisme
Par contre, je peux modifier les autres champs de la notice (tester sur Journal) et les autres mots clés de la notice (testé sur Association)
![bug1](https://user-images.githubusercontent.com/5398792/55000706-67d1b080-4fd3-11e9-9391-09ffa9f442b4.PNG)

![bug2](https://user-images.githubusercontent.com/5398792/55000720-6dc79180-4fd3-11e9-94c7-c6a1db08b638.PNG)

![bug3](https://user-images.githubusercontent.com/5398792/55000726-70c28200-4fd3-11e9-9857-fb4629d6c080.PNG)

En outre, dans le thésaurus, le terme est correct, je ne comprends donc pas pourquoi il me signale l’erreur

**Comment by daniel-menard** [comment]
Ah là, c'est subtil !

D'après l'url que vous donnez (http://www.documentation-sociale.net/recherche/?q=*&topic-prisme-hierarchy=ACTION%20%20HUMANITAIRE), mon oeil de vieil aigle vois qu'on a un double espace entre les mots "action" et "humanitaire" : ce sont les deux %20 que l'on a dans l'encodage de l'url.

Dans la liste des facettes, le mot-clé apparaît donc en rouge car le terme "action--humanitaire" (avec deux espaces) est un code qui n'existe pas. Par contre, à l'affichage, on n'a qu'un seul espace parce qu'en html les espaces ne sont pas significatifs (on pourrait en avoir un, deux ou cent, il n'en afficherait qu'un seul).

Lorsqu'on lance le chercher/remplacer, on a donc sélectionné toutes les notices (une seule) qui ont le mot-clé "action--humanitaire" et vous demandez à remplacer "action-humanitaire" (avec un seul espace cette fois), et forcément, il ne le trouve pas, et donc nous indique "zéro notices modifiées".

**Comment by daniel-menard** [comment]
Pour être complet, on a le même genre de subtilité quand on est en saisie/modification de notice : 

![image](https://user-images.githubusercontent.com/3940667/55007505-cdc43500-4fdf-11e9-9bbe-43cf055b323c.png)

Le terme est marqué "invalid" (parce que la version avec deux espaces n'existe pas dans le thesaurus), mais ça ne se voit pas à l'affichage (parce que les espaces ne sont pas significatifs en html).

**Comment by ocormont** [comment]
ok
