### ISSUE TITLE
Chercher Remplacer : sélection impossible

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#378]
http://www.documentation-sociale.net/recherche/?q=*&topic-prisme-hierarchy=AMANAGEMENT%20DE%20L%27ESPACE

Je veux modifier la notice, mais lorsque je clic sur Chercher Remplacer, un message m'indique 

![bug4](https://user-images.githubusercontent.com/5398792/55001602-3fe34c80-4fd5-11e9-8a36-7ad41c726f9e.PNG)

**Comment by daniel-menard** [comment]
C'est corrigé, c'était un bug dû à WordPress.
