### ISSUE TITLE
Chercher Remplacer et Réindexation

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#379]
J'ai modifié le Titre de revue Actualités sociales hebdomadaires ASH par Actualités sociales hebdomadaires (ASH)
Lorsque je retourne dans la recherche avancée, l'index du camp Revue indique toujours Actualités sociales hebdomadaires ASH, mais ne renvoie aucun résultat.
Est ce que cet index est réindexé  ?

**Comment by daniel-menard** [comment]
Oui c'est réindexé, mais les requêtes de type "lookup" sont mises en cache par le navigateur, donc la page "recherche avancée" peut afficher des entrées mises en cache mais qui n'existent plus.

La durée de mise en cache est variable selon le type de lookup : 10 minutes pour des lookups sur les index comme dans votre cas, pas de cache pour les lookups de type search, une semaine pour les lookups sur les entrées des tables d'autorité.

Il y a plusieurs solutions pour obtenir une réponse "à jour" et forcer le navigateur à mettre à jour son cache : 

- Faire F5 (ou shift+F5 ou ctrl+shift+F5 selon le navigateur) pour le forcer à recharger la page
- Vider le cache du navigateur
- Ouvrir une session "navigation privée" dans le navigateur

**Comment by ocormont** [comment]
ok
