### ISSUE TITLE
Contenus réservés aux adhérents

### ISSUE THREAD

**Issue by daniel-menard** [docalist/docalist#4]
![image](https://f.cloud.github.com/assets/3940667/909210/b5b0fb0a-fdb6-11e2-9535-53fcb7100d77.png)

Je n’avais pas relu ça, pouvons-nous l’appliquer ? : Droits d’accès spécifiques permettant de visualiser des menus et des contenus « privés » (Protégé par mot de passe ?). 

(e-mail de Nicolas du 03-08-13)

**Comment by Nicolas-L** [comment]
This issue was moved to reseau-prisme/site#3
