### ISSUE TITLE
Suprimer la maquette (/pages) du site .ORG

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#45]
La maquette qui est sur le .NET a été dupliquée sur le .ORG <http://www.documentation-sociale.net/pages/>. Elle se trouve donc en ligne sans barrière d'accès (login/mdp) <http://www.documentation-sociale.org/pages/>.
Il faudrait la supprimer du .ORG

**Comment by daniel-menard** [comment]
Dans le cadre de la migration de subversion vers git, j'ai créé un dépôt spécifique (projet privé sur bitbucket) pour stocker le code de la maquette (jusque là, c'était stocké dans le dépôt principal du site).

Lorsque les sites seront recréés à partir des dépôts git, cela permettra de ne plus avoir la maquette sur le site .org, et on aura le choix de l'installer ou non sur le .net.

**Comment by daniel-menard** [comment]
Les sites ont été recréés à partir des dépôts git, la maquette n'est plus accessible.
